# Fabric
loader_version=0.19.3
fabric_version=0.138.4+1.21.10

# Minecraft
minecraft_version=1.21.10
yarn_mappings=1.21.10+build.3

# Loom
loom_version=1.17.19

# Kotlin
kotlin_version=2.4.10
flk_version=1.13.13+kotlin.2.4.10

# Mod
mod_version=0.1.0
maven_group=dev.ggtv
archives_base_name=capecraft

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true